In [1]:
import numpy as np
import tensorflow as tf

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [11]:
vocab_size = 100
encoded_reviews = [tf.keras.preprocessing.text.one_hot(r, vocab_size) for r in reviews]
encoded_reviews

[[83, 61],
 [45, 41],
 [66, 31],
 [71, 88, 28],
 [54, 18, 99],
 [96, 61],
 [17, 18, 40],
 [9, 72],
 [9, 94],
 [31, 11]]

In [10]:
max_length = max(len(r) for r in encoded_reviews) + 1
padded_reviews = tf.keras.preprocessing.sequence.pad_sequences(encoded_reviews, max_length, padding='post')
padded_reviews

array([[83, 61,  0,  0],
       [45, 41,  0,  0],
       [66, 31,  0,  0],
       [71, 88, 28,  0],
       [54, 18, 99,  0],
       [96, 61,  0,  0],
       [17, 18, 40,  0],
       [ 9, 72,  0,  0],
       [ 9, 94,  0,  0],
       [31, 11,  0,  0]])

In [12]:
embended_vector_size = 5
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(vocab_size, embended_vector_size, input_length=max_length, name='embending'))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embending (Embedding)       (None, 4, 5)              500       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 521
Trainable params: 521
Non-trainable params: 0
_________________________________________________________________


In [15]:
X = padded_reviews
y = sentiment

model.fit(X, y, epochs=50, verbose=0)

In [16]:
model.evaluate(X, y)

1/1 [==============================] - 0s 25ms/step - loss: 0.6200 - accuracy: 1.0000


[0.6200312376022339, 1.0]

In [21]:
weights = model.get_layer('embending').get_weights()[0]
len(weights)

weights[83], weights[45], weights[31]

(array([ 0.03686148, -0.0256776 ,  0.08381927,  0.03607658, -0.01917528],
       dtype=float32),
 array([ 0.08851508, -0.03433585,  0.02438495,  0.06129123, -0.01740792],
       dtype=float32),
 array([-0.08884708, -0.01373216, -0.06005771,  0.076675  ,  0.09527443],
       dtype=float32))